### ISSUE TITLE
ᚫ.r Potential unintended behavior

### ISSUE THREAD

**Issue by NekoNoka** [crackalamoo/futhorc#1]
In the updateText function there are lines which seem to work unintentionally

```js
601: const PUNCT = ['.', ',', ':', ';', '!', '?', ')'];
602: for (const punct of PUNCT) {
603:     t = t.replaceAll(punct, ' ' + punct);
604: }
```

This adds a space which I'm sure is intended however it causes unintended side effects directly afterwards.

```js
605: t = t.replaceAll("ᚫ ", "ᚪ ");
606: t = t.replaceAll("ᛁᛁ ", "ᛁ "); // /i/ simplified word-finally
607: t = t.replaceAll("ᛟ ", "ᚩ ");
```

Any of these examples typed into the website will behave like so.

```
"a." -> "ᚪ."
"ee." -> "ᛁ."
"o." -> "ᚩ."
```

Example of expected and actual output

```
input:
a.r
expected:
ᚫᚱ
actual:
ᚪ.ᚱ
```

I'm not sure the correct overall behavior since I am not familiar with phonetics but I am sure this is unintended somewhat.
I assume It is predicting the period as closing off the end of the "word" and producing a predicted cap off for it.
I only discovered this as I attempted to type directly "ᚫ.r" and was confused why the vowel was changing before finishing with "r".
I would submit a code change but since I am not familiar with phonetics and don't know the overall implications for any changes I might make I can only make a new issue for you.

I really like this project you did good!

**Comment by crackalamoo** [comment]
Thank you for your feedback! Confusing a period for the end of the word was in fact the issue. This should be fixed now (commit b4bfa06).
